@startuml 大原情報科学大学・図書館システム
skinparam componentStyle rectangle

' 学生
' 名前、生年月日、専門分野、入学年月日、卒業年月日
[訪問者] o-- [登録]
[訪問者] o-- [参照]
[訪問者] o-- [ユーザーID]
[訪問者] o-- [パスワード]
[訪問者] o-- [名前]
[訪問者] o-- [学校名]
[訪問者] o-- [所属名]
[訪問者] o-- [メールアドレス]
@enduml