@startuml 大原情報科学大学・図書館システム
skinparam componentStyle rectangle

' Robodog
[図書館システム] o-- [利用者]
[図書館システム] o-- [貸出]
[図書館システム] o-- [返却処理]
[図書館システム] o-- [管理番号]
[管理番号] o-- [書名]
[貸出] o-- [学生証]
[貸出] o-- [職員証]
[返却処理] o-- [借りた本]
[図書館システム] o-- [会員]
[会員] o-- [会員番号]
[利用者] o-- [予約]
[予約] o-- [予約カード]
[予約カード] o-- [学生番号]
[予約カード] o-- [職員番号]



@enduml