@startuml Robodogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -MyName:String
 -myTime:int
 -goodMorning:String
 -goodafternoon:String
 -goodNight:String
 -firstvalue:int
 -secondValue:int
 '教科書にない
 -result:int
'返り値
+getMyName():String
+setMyName():int
+setNewTime():void
+getMyGreeting():String
 '教科書にない
+setTwoValues():void
+setAndGetResult():int
}

@enduml
